提交图的最短路径
CUCCS/ds pull request #162
Opened 2017-05-25 12:40 UTC by Loxjan

提交求图的任意两点间最短路径的算法。

2017-06-04 11:51 UTC, chenfucaijun requested changes

2017-06-04 11:51 UTC, chenfucaijun commented on 2017-1/Micylt/hw7/Graph.c
> +	G->matrix[0][1] = 1;
* 一个循环就能搞定，这样写多不好看啊

2017-06-04 11:51 UTC, chenfucaijun commented on 2017-1/Micylt/hw7/Graph.h
> +#define MAX 20 //��󶥵����
* 这些全局定义统一放到最上面会更美观

2017-06-04 11:59 UTC, chenfucaijun requested changes

2017-06-04 11:59 UTC, chenfucaijun commented on 2017-1/Micylt/hw8/BSTOutput.txt
> +8, 3, 1, 6, 4, 5, 7, 10, 14, 19, 22, 30
* 程序中没有看到C语言文件流相关操作，这个结果输出是手工复制的吗? 建议使用C语言文件操作，自动把查找结果输出到文件中

2017-06-04 16:11 UTC, Loxjan commented on 2017-1/Micylt/hw8/BSTOutput.txt
> +8, 3, 1, 6, 4, 5, 7, 10, 14, 19, 22, 30
= =，不好意思理解错了，结果确实是自己复制的.... 修改后会重新提交

2017-06-05 07:10 UTC, Loxjan commented
按师哥要求修改后再次提交

2017-06-12 08:57 UTC, Loxjan commented
按要求修改后再次提交

2026-05-24 06:04 UTC, closed without merging